//
//  UIColor+HLMColors.h
//
//  Generated by Zeplin on 8/27/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (HLMColors)

+ (UIColor *)hlm_lightGrayColor;
+ (UIColor *)hlm_lightPinkColor;
+ (UIColor *)hlm_themPinkColor;
+ (UIColor *)hlm_darkGrayColor;
+ (UIColor *)hlm_lightWhiteBgColor;
+ (UIColor *)hlm_borderColor;
+ (UIColor *)hlm_titleGrayColor ;

+ (UIColor *)hlm_brownishGreyColor;
+ (UIColor *)hlm_warmGreyColor;
+ (UIColor *)hlm_carnationColor;

+ (UIColor *)hlm_backGroundColor;

@end
