//
//  UIColor+HLMColors.m
//
//  Generated by Zeplin on 8/27/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+HLMColors.h"

@implementation UIColor (HLMColors)

+ (UIColor *)hlm_lightGrayColor {
    return [UIColor colorWithRed:153.0f / 255.0f green:167.0f / 255.0f blue:178.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_lightPinkColor {
    return [UIColor colorWithRed:255.0f / 255.0f green:168.0f / 255.0f blue:197.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_themPinkColor {
    return [UIColor colorWithRed:255.0f / 255.0f green:115.0f / 255.0f blue:133.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_darkGrayColor {
    return [UIColor colorWithRed:128.0f / 255.0f green:141.0f / 255.0f blue:149.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_titleGrayColor {
    return [UIColor colorWithRed:102.0f / 255.0f green:102.0f / 255.0f blue:102.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_lightWhiteBgColor {
    return [UIColor colorWithWhite:240.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_borderColor {
    return [UIColor colorWithWhite:227.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_brownishGreyColor{
    return [UIColor colorWithRed:102.0f / 255.0f green:102.0f / 255.0f blue:102.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_warmGreyColor{
    return [UIColor colorWithRed:153.0f / 255.0f green:153.0f / 255.0f blue:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_carnationColor{
    return [UIColor colorWithRed:255.0f / 255.0f green:115.0f / 255.0f blue:133.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hlm_backGroundColor{
    return [UIColor colorWithRed:246.0f / 255.0f green:246.0f / 255.0f blue:246.0f / 255.0f alpha:1.0f];
}
@end
